export const design = {
  fontFamily: {
    montserrat: "'Montserrat', sans-serif",
    fredoka: "'Fredoka', sans-serif",
    ibmPlexSansKR: "'IBM Plex Sans KR', sans-serif",
    permanentMarker: "'Permanent Marker', cursive",
  },
  fontWeight: {
    light: 300,
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  fontSize: {
    tit: { default: "6vw", breakpoint: "72px" },
    xxl: { default: "96px", breakpoint: "72px" },
    xl: { default: "72px", breakpoint: "48px" },
    lg: { default: "48px", breakpoint: "36px" },
    md: { default: "36px", breakpoint: "24px" },
    sm: { default: "24px", breakpoint: "20px" },
    xs: { default: "20px", breakpoint: "18px" },
    xxs: { default: "18px", breakpoint: "14px" },
  },
  fontStyle: {
    normal: "normal",
    italic: "italic",
  },
  lineHeight: {
    wide: "150%",
    normal: "120%",
    tight: "100%",
  },
  letterSpacing: {
    tight: "-0.05em",
    normal: "0",
    wide: "0.05em",
  },
  textDecoration: {
    none: "none",
    underline: "underline",
  },
  textTransform: {
    none: "none",
    uppercase: "uppercase",
    lowercase: "lowercase",
  },
  textAlign: {
    left: "left",
    center: "center",
    right: "right",
  },
  whiteSpace: {
    normal: "normal",
    nowrap: "nowrap",
    preWrap: "pre-wrap",
    breakSpace: "break-spaces",
  },
  colors: {
    purple: "#d05fe5",
    deepPurple: "#310591",
    yellow: "#ffe30d",
    lemonYellow: "#f7ff2f",
    green: "#2ea34e",
    lime: "#89de07",
    cyan: "#41e0eb",
    coral: "#f06b67",
    pink: "#ff7896",
    white: "#fff",
    gray100: "#f9f9f9",
    gray200: "#f5f5f5",
    gray300: "#f1f1f1",
    gray400: "#eaeaea",
    gray500: "#ddd",
    gray600: "#aaa",
    gray700: "#666",
    gray800: "#555",
    gray900: "#444",
    blackLight: "#333",
    blackMedium: "#222",
    black: "#111",
  },
  opacities: {
    opaque: 1,
    semiOpaque: 0.8,
    translucent: 0.6,
    semiTransparent: 0.4,
    transparent: 0.2,
    invisible: 0,
  },
};
